Leader Board: Add the new style
batoorsohail/leaderboard pull request #5
Opened 2023-02-16 20:10 UTC by batoorsohail

### In this project, we added the following:

- [ ] Background linear color
- [ ] Overflow to scroll down
- [ ] New style 
- [ ] Mobile version

2023-02-16 20:52 UTC, Rustamxon7 requested changes
Hello @batoorsohail,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
_Your project is almost complete!_
_No Linters errors_

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Check the comments under the review._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 20:52 UTC, Rustamxon7 commented on README.md
>  ### Install
@batoorsohail You did great job!

- [ ] I like the styling. However, we have some parts in your README.md are missing. It should have instructions about where and how to generate any necessary keys, credentials, how to set, store, and generate them

They are placed in this section:


```
Install
Install this project with:   ----> install with ?

Usage
To run the project, execute the following command: ----> what command ?

Run tests
To run tests, run the following command: ----> what command ?

Deployment
You can deploy this project using: ----> using what ?
```

Kindly fill gaps in this sections. Also you are free to remove unnecessary parts from it such as how to deply.

2023-02-16 20:53 UTC, Rustamxon7 commented on README.md
>  ### Install
Also, in Acknowledgment:

```
I would like to thank... who/what?
```

2023-02-17 06:07 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @batoorsohail, 👋 👋  

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

## Good Points 👍

- Has a proper Pull Request. ✔️
- No Linter errors ✔️
- Good use of Git flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 06:15 UTC, merged